region: us-east-1

function_name: parser
handler: service.handler
description: post parser
runtime: python3.6
role: lambda_basic_execution
memory_size: 128
timeout: 15

environment_variables:
  SNS_ARN: ${VIZLAB_PARSER_SNS_ARN}
  DATABASE_URI: ${VIZLAB_DATABASE_URI}

build:
  source_directories: lib, psycopg2

bucket_name: 'vizlab-lambda'
s3_key_prefix: 'parser/'

subnet_ids: [subnet-4f0f4860]
security_group_ids: [sg-e26de795, sg-0f168278]
