region: us-east-1

function_name: downloader
handler: service.handler
description: image downloader
runtime: python3.6
role: lambda_basic_execution
memory_size: 128
timeout: 15

build:
  source_directories: lib

