region: us-east-1

function_name: downloader
handler: service.handler
description: image downloader
runtime: python3.6
role: lambda_basic_execution
memory_size: 128
timeout: 15

environment_variables:
  S3_BUCKET: ${VIZLAB_S3_BUCKET}
  REDIS_URI: ${VIZLAB_REDIS_URI}
  DATABASE_URI: ${VIZLAB_DATABASE_URI}

build:
  source_directories: lib, psycopg2, PIL, numpy

bucket_name: 'vizlab-lambda'
s3_key_prefix: 'downloader/'

subnet_ids: [subnet-4f0f4860]
security_group_ids: [sg-e26de795, sg-0f168278]
