region: us-east-1

function_name: arbiter
handler: service.handler
description: pulls threads for scrapers to process
runtime: python3.6
role: lambda_basic_execution
timeout: 60
memory_size: 128

environment_variables:
  REDIS_URI: ${VIZLAB_REDIS_URI}
  SNS_ARN: ${VIZLAB_ARBITER_SNS_ARN}
  DATABASE_URI: ${VIZLAB_DATABASE_URI}

build:
  source_directories: lib, psycopg2

bucket_name: 'vizlab-lambda'
s3_key_prefix: 'arbiter/'

subnet_ids: [subnet-4f0f4860]
security_group_ids: [sg-e26de795, sg-0f168278]
