region: us-east-1

function_name: sources
handler: service.handler
description: interface to manage sources
runtime: python3.6
role: lambda_basic_execution
timeout: 15
memory_size: 128

environment_variables:
  REDIS_URI: ${VIZLAB_REDIS_URI}
  DATABASE_URI: ${VIZLAB_DATABASE_URI}
  SOURCES: ${VIZLAB_SOURCES}

build:
  source_directories: lib, psycopg2

bucket_name: 'vizlab-lambda'
s3_key_prefix: 'sources/'

subnet_ids: [subnet-4f0f4860]
security_group_ids: [sg-e26de795, sg-0f168278]
