region: us-east-1

function_name: scraper
handler: service.handler
description: generic scraper
runtime: python3.6
role: lambda_basic_execution
memory_size: 128
timeout: 15

build:
  source_directories: lib

